name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


assets:
  - assets/imgs/corrida1.png
  - assets/imgs/corrida2.png
  - assets/imgs/corrida3.png
  - assets/imgs/corrida4.png
  - assets/imgs/corrida.png
  - assets/imgs/btn1.png
  - assets/imgs/btn2.png
  - assets/imgs/btn3.png
  - assets/imgs/btn4.png
  - assets/imgs/bike1.png
  - assets/imgs/bike2.png
  - assets/imgs/bike3.png
  - assets/imgs/bike4.png
  - assets/imgs/bike5.png
  - assets/imgs/nata1.png
  - assets/imgs/nata2.png
  - assets/imgs/nata3.png
  - assets/imgs/nata4.png
  - assets/imgs/nata5.png
  - assets/imgs/fute1.png
  - assets/imgs/fute2.png
  - assets/imgs/fute3.png
  - assets/imgs/fute4.png
  - assets/imgs/fute5.png
  
